### ISSUE TITLE
Fix all eslint problems in the project

### ISSUE THREAD

**Issue by emersonlaurentino** [vtex/styleguide#1082]
There are currently a lot of errors and warnings because of the eslint update in #1080.

The purpose of this issue is to fix all the eslint errors that currently exist so that issue #1081 can be resolved.

Files:
- [x] `/codemod/__tests__/button-v4.test.js`
- [x] `/codemod/button-v4.js` #1216 
- [x] `/config/env.js` #1092
- [x] `/config/jest/fileTransform.js` #1092
- [x] `/config/polyfills.js` #1092
- [x] `/config/test.js` #1092
- [x] `/config/webpack.config.js` #1092
- [x] `/react/EXPERIMENTAL_Conditions.js` #1214 
- [x] `/react/components/Alert/index.js` #1091
- [x] `/react/components/Alert/index.test.js` #1091
- [x] `/react/components/AutocompleteInput/SearchInput/index.tsx` #1231 
- [x] `/react/components/AutocompleteInput/index.tsx` #1231 
- [x] `/react/components/Button/index.test.tsx`#1118
- [x] `/react/components/Button/index.tsx`#1118
- [x] `/react/components/ButtonPlain/index.tsx` #1230 
- [x] `/react/components/ColorPicker/ColorHistory.js` #1207 
- [x] `/react/components/ColorPicker/HexInput.js` #1207 
- [x] `/react/components/ColorPicker/index.js` #1207 
- [x] `/react/components/Conditions/StrategySelector.tsx` #1167
- [x] `/react/components/Conditions/index.tsx` #1167
- [x] `/react/components/DatePicker/index.js` #1210 
- [x] `/react/components/Dropdown/index.js` #1210 
- [x] `/react/components/Dropzone/index.js` #1104
- [x] `/react/components/EXPERIMENTAL_Charts/BarChart/index.tsx` #1232 
- [x] `/react/components/EXPERIMENTAL_Conditions/Atoms/ObjectAtom.js`
- [x] `/react/components/EXPERIMENTAL_Conditions/Atoms/SubjectAtom.js`
- [x] `/react/components/EXPERIMENTAL_Conditions/Atoms/VerbAtom.js`
- [x] `/react/components/EXPERIMENTAL_Conditions/Statement.js`
- [x] `/react/components/EXPERIMENTAL_Conditions/StrategySelector.js`
- [x] `/react/components/EXPERIMENTAL_Conditions/index.js`
- [x] `/react/components/EXPERIMENTAL_Select/MultiValueRemove.js` #1215 
- [x] `/react/components/EXPERIMENTAL_Select/index.js` #1215 
- [x] `/react/components/EXPERIMENTAL_Table/Checkbox.tsx` #1224 
- [x] `/react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx` #1224 
- [x] `/react/components/EXPERIMENTAL_Table/Toolbar/PopoverMenu.tsx` #1224 
- [x] `/react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx` #1224 
- [x] `/react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts` #1224 
- [x] `/react/components/EXPERIMENTAL_useCheckboxTree/index.tsx` #1223 
- [x] `/react/components/EXPERIMENTAL_useCheckboxTree/util.ts` #1223 
- [x] `/react/components/FilterBar/FilterTag.js` #1106
- [x] `/react/components/FilterBar/Menu.js` #1106
- [x] `/react/components/Input/index.js` #1105
- [x] `/react/components/InputCurrency/index.js` #1105
- [x] `/react/components/InputPassword/index.js` #1105
- [x] `/react/components/InputSearch/index.js` #1105
- [x] `/react/components/Modal/TopBar.js` #1102
- [x] `/react/components/ModalDialog/index.js` #1102
- [x] `/react/components/MultiSelect/DropdownList.js` #1212 
- [x] `/react/components/NumericStepper/index.js` #1212 
- [x] `/react/components/Radio/index.js` #1212 
- [x] `/react/components/RadioGroup/index.js` #1212 
- [x] `/react/components/SelectableCard/index.tsx` #1103
- [x] `/react/components/Slider/Selector.js`#1103
- [x] `/react/components/Slider/index.js` #1103
- [x] `/react/components/Statement/Atoms/SubjectAtom.tsx` #1233 
- [x] `/react/components/Table/BulkActions.js` #1211 
- [x] `/react/components/Table/CheckboxContainer.js` #1211 
- [x] `/react/components/Table/SimpleTable.js` #1211 
- [x] `/react/components/Table/Toolbar.js` #1211 
- [x] `/react/components/Table/index.js` #1211 
- [x] `/react/components/Textarea/index.js` #1234 
- [x] `/react/components/ToastProvider/Toast.js` #1103
- [x] `/react/components/ToastProvider/ToastManager.js` #1103
- [x] `/react/components/ToastProvider/index.js` #1103
- [x] `/react/components/Tooltip/Portal.tsx` #1235 
- [x] `/react/components/Tooltip/TooltipPopup.tsx` #1235 
- [x] `/react/components/Tooltip/hooks.ts` #1235 
- [x] `/react/components/Tooltip/utils/dom.ts` #1235 
- [x] `/react/components/index.js` #1214 
- [x] `/react/modules/deprecated.tsx` #1160
- [x] `/scripts/entrypoints.js` #1160
- [x] `/scripts/version.js` #1160
- [x] `/styleguide.config.js` #1160
- [x] `/styleguide.styles.js` #1160

**Comment by emersonlaurentino** [comment]
I will fix the file problems:

- /react/modules/deprecated.tsx
- /scripts/entrypoints.js
- /scripts/version.js
- /styleguide.config.js
- /styleguide.styles.js

**Comment by thayannevls** [comment]
I will fix these ones:

- /react/components/Tooltip/Portal.tsx
 - /react/components/Tooltip/TooltipPopup.tsx
-  /react/components/Tooltip/hooks.ts
- /react/components/Tooltip/utils/dom.ts
- /react/components/index.js

**Comment by igorbrasileiro** [comment]
> I will fix the EXPERIMENTALS problems

I solved from ButtonGroup

**Comment by igorbrasileiro** [comment]
I will fix these ones:
- /react/components/Conditions/StrategySelector.tsx
-  /react/components/Conditions/index.tsx

**Comment by igorbrasileiro** [comment]
I have a doubt, what to do with DIVs with `onClick` property?

**Comment by thayannevls** [comment]
@igorbrasileiro add `role="button"` for now. We will look for a better solution for this in the future :smile:

**Comment by matheusps** [comment]
🥳 Done
